spring:
  application:
    name: user-service
server:
  port: 8001
eureka:
  client:
    service-url:
      defatultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
